### ISSUE TITLE
最新版本 无法获取到USDT的转账数据

### ISSUE THREAD

**Issue by xiaoyi510** [v03413/bepusdt#33]
最新版本 无法获取到USDT的转账数据

TG 无通知
查询订单 也未支付

但是获取币链接是能获取到余额

**Comment by xiaoyi510** [comment]
使用docker 香港服务器
容器无报错

**Comment by xiaoyi510** [comment]
docker-compose 文件
```
version: "3.3"
services:
  bepusdt:
    restart: always
    ports:
      - 8080:8080
    environment:
      - TG_BOT_TOKEN=xxxx
      - TG_BOT_ADMIN_ID=xxxx
      - USDT_RATE=~0.98
      - APP_URI=https://xxxx.com
    volumes:
      - /www/wwwroot/docker_compose/bepusdt/bepusdt.db:/runtime/bepusdt.db
    image: v03413/bepusdt:latest
networks: {}

```
