### ISSUE TITLE
加一个docker compose 方便部署

### ISSUE THREAD

**Issue by markwhitey** [v03413/bepusdt#74]
```yml
services: 
  bepusdt: 
    image: v03413/bepusdt:beta 
    container_name: bepusdt 
    restart: unless-stopped 
    ports: 
      - "8080:8080" 
    volumes: 
      - ./conf.toml:/usr/local/bepusdt/conf.toml
      - ./data:/var/lib/bepusdt
```
